### PR TITLE
Update LQSViewController.m

### PR DESCRIPTION
**Pull request by tuchangwei**
make the simulator and the device in the same conversation.

### CODE REVIEW

**Comment by tuchangwei** [comment]
make the simulator and the device in the same conversation.

**Comment by maju6406** [comment]
We haven't seen this problem, and not sure how your PR fixes the issue. There should only be 1 distinct conversation between simulator and device so it shouldn't matter if you're retrieving the first or last conversation.

**Comment by tuchangwei** [comment]
Sometimes, the simulator and the device are in different conversations, I don't know if you met the situation.

As I tested, sometimes, the simulator's nav colour is not changed even though the device's nav colour is changed. That means the meta data is not sync sometimes.

And I have a question is: why I can't query the conversations which have messages using the following code:

let query = LYRQuery(queryableClass: LYRConversation.self)
let amInpredicate = LYRPredicate(property: "participants", predicateOperator: LYRPredicateOperator.IsIn, value: GHOSTLayerClient.authenticatedUserID)
 let messageIsNilPredicate = LYRPredicate(property: "lastMessage", predicateOperator: LYRPredicateOperator.IsNotEqualTo, value: nil)
query.predicate = LYRCompoundPredicate(type: .And, subpredicates: [amInpredicate,messageIsNilPredicate])
//        query.predicate = amInpredicate
query.sortDescriptors = [NSSortDescriptor(key: "lastMessage.receivedAt", ascending: false)] self.queryController = GHOSTLayerClient.queryControllerWithQuery(query)

It will crash with the error "no such column: last_message_object_identifier", the document said the "lastMessage" is queryable.

I have to use the above code to query the conversations, because I also need to detect the change of these conversation.

Thanks.

**Comment by tuchangwei** [comment]
Sorry, I read the document again, I think if I want to delete the message history, I should delete the conversation with local mode.

But I also found the meta data of the conversation is gone after I deleted the conversation with local mode. I have submit another PR, please check it, Thanks.

**Pull request closed without merging**
